name: Build AHK EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download AutoHotkey Portable
      run: |
        curl -L -o ahk.zip https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.37.02/AutoHotkey_1.1.37.02.zip
        powershell Expand-Archive ahk.zip -DestinationPath ahk

    - name: Compile script
      run: |
        ahk\Compiler\Ahk2Exe.exe /in mouse_move.ahk /out output\mouse_move.exe

    - name: List output files (debug)
      run: |
        dir output

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: mouse_move_exe
        path: output\mouse_move.exe
