name: Build AHK EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Ahk2Exe
      run: |
        Invoke-WebRequest "https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.37.02/Ahk2Exe.zip" -OutFile Ahk2Exe.zip
        Expand-Archive Ahk2Exe.zip -DestinationPath Ahk2Exe

    - name: Create output directory
      run: |
        New-Item -ItemType Directory -Force -Path output

    - name: Compile script
      run: |
        & ".\Ahk2Exe\Ahk2Exe.exe" /in mouse_move.ahk /out (Join-Path $PWD "output\mouse_move.exe")

    - name: List output files
      run: |
        Get-ChildItem output

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: mouse_move_exe
        path: output/mouse_move.exe
