name: Build AHK EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download AutoHotkey Portable
      run: |
        curl -L -o ahk.zip https://github.com/AutoHotkey/AutoHotkey/releases/download/v1.1.37.02/AutoHotkey_1.1.37.02.zip
        powershell Expand-Archive ahk.zip -DestinationPath ahk

    - name: Create output directory
      run: |
        mkdir output

    - name: Find Ahk2Exe
      run: |
        dir ahk /s /b | findstr Ahk2Exe.exe

    - name: Compile script (auto path)
      run: |
        for /f "delims=" %i in ('dir ahk /s /b ^| findstr Ahk2Exe.exe') do "%i" /in mouse_move.ahk /out output\mouse_move.exe

    - name: List output files
      run: |
        dir output

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: mouse_move_exe
        path: output\mouse_move.exe
